### ISSUE TITLE
Unable to boot host

### ISSUE THREAD

**Issue by bauerj** [gebn/beam#2]
Using this code from the example:

     [host.boot() for host in beam.hosts() if not host.is_online]

I get this error:

```
Traceback (most recent call last):
  File "boot.py", line 3, in <module>
    [host.boot() for host in beam.hosts() if not host.is_online]
  File "/usr/local/lib/python2.7/dist-packages/beam/host.py", line 148, in boot
    self.action('boot')
  File "/usr/local/lib/python2.7/dist-packages/beam/host.py", line 131, in action
    data = self.identity.request_params
AttributeError: 'Host' object has no attribute 'identity'

```

**Comment by gebn** [comment]
Fixed in [v0.4.0, released just now](https://pypi.python.org/pypi/beam).
