### ISSUE TITLE
certificate verify failed

### ISSUE THREAD

**Issue by gelavat** [gebn/beam#6]
Hello,

I get the following error when I try to connect to my host using beam. It seems it is due to the access to an HTTPS URL:
certificate verify failed

I am using Python 3.6 on Windows 10 64bits, with beam V0.5.0.

An idea of how to solve this issue?

Thank you.
Regards.
Gelavat

P.S: Below is the full error, with test1 being a replacement for the real host to hide it:

>>> host_temp = beam.host('test1')
Traceback (most recent call last):
  File "C:\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "C:\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "C:\Python\Python36-32\lib\site-packages\urllib3\connection.py", line 356, in connect
    ssl_context=context)
  File "C:\Python\Python36-32\lib\site-packages\urllib3\util\ssl_.py", line 359, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Python\Python36-32\lib\ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "C:\Python\Python36-32\lib\ssl.py", line 814, in __init__
    self.do_handshake()
  File "C:\Python\Python36-32\lib\ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Python\Python36-32\lib\ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\Python36-32\lib\site-packages\requests\adapters.py", line 445, in send
    timeout=timeout
  File "C:\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Python\Python36-32\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='manage.test1.com', port=443): Max retries exceeded with url: /api/client/command.php?key=xx&hash=xx&action=info&ipaddr=true&hdd=true&mem=true&bw=true&status=true (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#15>", line 1, in <module>
    host_temp = beam.host('test1')
  File "C:\Python\Python36-32\lib\site-packages\beam\__init__.py", line 35, in host
    return Host.request_from_identity(identity)
  File "C:\Python\Python36-32\lib\site-packages\beam\host.py", line 182, in request_from_identity
    identity.vendor.endpoint + cls._ENDPOINT, params=params)
  File "C:\Python\Python36-32\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python\Python36-32\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python\Python36-32\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python\Python36-32\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python\Python36-32\lib\site-packages\requests\adapters.py", line 511, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='manage.test1.com', port=443): Max retries exceeded with url: /api/client/command.php?key=xx&hash=xx&action=info&ipaddr=true&hdd=true&mem=true&bw=true&status=true (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),))
>>>

**Comment by gebn** [comment]
Beam must be pointed to the SolusVM control plane rather than your node. Ask your provider if you're unsure where this is.
